version: '3.8'

services:
  facturacion-app:
    image: ghcr.io/elitealma/facturacion:main
    networks:
      - traefik_default # Este suele ser el nombre por defecto si tu stack se llama 'traefik'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.facturacion-elite.rule=Host(`facturacion.pegasus360agency.com`)"
      - "traefik.http.routers.facturacion-elite.entrypoints=websecure"
      - "traefik.http.routers.facturacion-elite.tls.certresolver=myresolver"
      - "traefik.http.services.facturacion-elite.loadbalancer.server.port=80"
    restart: always

networks:
  traefik_default:
    external: true
